### ISSUE TITLE
Revamp Footer

### ISSUE THREAD

**Issue by RahulBansal0502** [garg3133/JagratiWebApp#180]
I want to change the footer. Also when we click on the event it directed to home. Please assign this issue to me.

**Comment by garg3133** [comment]
@RahulBansal0502 What changes do you propose for the footer?

**Comment by RahulBansal0502** [comment]
![image](https://user-images.githubusercontent.com/56486309/111900316-d5e0cf00-8a57-11eb-9bb2-28287f6f28fb.png)

We have to make a footer of this type. And also the contact us section I wants that in half section vertically there will be a map and in half section, there is a contact form or if not want to add form then instead of this we add contact details like this

![contact](https://user-images.githubusercontent.com/56486309/111900672-e85c0800-8a59-11eb-8c93-515d3800be8c.png)

Also, we are using multiple colours on our website like black, white, grey, yellow, orange so its my suggestion we can use limited colours like this website is for the social cause then we can use colours mainly yellow, white and orange which are also present in our logo.

Please assign these issues to me. I am a participant in GSSOC 2021.

**Comment by garg3133** [comment]
@tmo66 Can you comment on this?

**Comment by tmo66** [comment]
Hey @RahulBansal0502, I think the current footer looks much better than the one you proposed and as far as colors are concerned, they are derived from the logo of Jagrati, it has yellow, black, and red in it. 

By the way, I'm pretty much impressed that you observed that the event in the navbar redirects to the home page, instead of a specific page, but that work is still in progress and we are developing a page for that.
(I'm closing this issue for now )
