### ISSUE TITLE
[bug]: Contact us section in the New Home page.

### ISSUE THREAD

**Issue by tushhr** [garg3133/JagratiWebApp#216]
**Describe the bug**
Contact us section behaves absurdly when screen length is greater than 690px.

**To Reproduce**
1. Go to `\new`
2. Head over to the contact us section.
3. Minimize the screen width.

**Expected behavior**
Good responsive behavior.

**Screenshots**
![image](https://user-images.githubusercontent.com/63875632/113328252-a96f6180-9339-11eb-8d1a-8bf59d9e5b6c.png)

**Additional context**

**Comment by tanishq-arya** [comment]
I cannot see the new home page. Can you help me with it ?

**Comment by garg3133** [comment]
@tanishq-arya New home page is available at http://localhost:8000/new

**Comment by Saatvik21** [comment]
I want to work on this issue.

PS- I tried working on it but like couldn't well fix it. Is there any way to overwrite the bootstrap columns properties cuz that's the only fix I found when trying to add flex properties to it

**Comment by garg3133** [comment]
Sure @Saatvik21, assigning you the issue.

For the small screens, you can just bring the two cards in rows instead of columns and also reduce the padding inside the card so that everything appears in a single line (like the phone number, connect with us and its icons).

You can use `!important` tag if you want to overwrite a property.
